version: '3.3'
services:
  # web:
  #   image: nginx
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./config/nginx
  #   volumes:
  #     - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - '8080:80'
  #   environment:
  #     - NGINX_HOST=thisisatestfoobar.com
  #     - NGINX_PORT=80

  db:
    image: duynguye/mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '5000:80'
    links:
      - db

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content/
    ports:
      - '4000:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data: {}
